force-app/main/default/objects/Contact/fields/HAM_Current_Chapters__c.field-meta.xml
<CustomField>
    <fullName>HAM_Current_Chapters__c</fullName>
    <label>Current Chapters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HAM_Name_w_Suffix__c.field-meta.xml
<CustomField>
    <fullName>HAM_Name_w_Suffix__c</fullName>
    <formula>ucinn_ascendv2__Full_Name_Formula__c&amp;&quot; &quot;&amp;HAM_Institutional_Suffix__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name w/Suffix</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HAM_Preferred_Chapter_Lookup__c.field-meta.xml
<CustomField>
    <fullName>HAM_Preferred_Chapter_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the Chapter for which Preferred is True</description>
    <label>Preferred Chapter Lookup</label>
    <referenceTo>HAM_Chapter_Lookup__c</referenceTo>
    <relationshipLabel>Constituents (Preferred Chapter Lookup)</relationshipLabel>
    <relationshipName>Constituents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HAM_Chapter_Lookup__c/HAM_Chapter_Lookup__c.object-meta.xml
<CustomObject>
    <description>Chapter/Region lookup table</description>
    <label>Chapter Lookup</label>
    <nameField>
        <label>Chapter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapter Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HamMyProspectController.cls
public with sharing class HamMyProspectController {
     @AuraEnabled(cacheable=true)
    public static List<Contact> searchMyProspects() {
        Id userId =UserInfo.getUserId(); 
        List<Contact> recentlyViewedRecords= [SELECT ID, Name,HAM_Name_w_Suffix__c,HAM_Preferred_Chapter_Lookup__c,HAM_Preferred_Chapter_Lookup__r.name, HAM_Current_Chapters__c FROM Contact WHERE ucinn_ascendv2__PRM__c =:userId ORDER BY LastViewedDate DESC];
        system.debug('recentlyViewedRecords-----'+recentlyViewedRecords);
        return recentlyViewedRecords;
    }
}